### ISSUE TITLE
Rebuilding updated tag still refers to old commit id

### ISSUE THREAD

**Issue by pardom** [jitpack/jitpack.io#1025]
I made a change to the repo and updated the tag to a new commit id. Then I deleted the Jitpack build and started a new build. The new build always refers to the original commit id. Doing this has worked for me in the past and even works at present for other repositories. Additionally, the resulting artifact does not represent the commit id source.

Build log: https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.0/build.log
Original commit id: [c9c40602c6ccd8a052549cf751e05e87d4d63d8e](https://github.com/pardom/redux-observable-kotlin/commit/c9c40602c6ccd8a052549cf751e05e87d4d63d8e)
Updated commit id: [7fa50b4f39f5eadd2f55880530abef8965cb81cc](https://github.com/pardom/redux-observable-kotlin/releases/tag/1.2.0)

**Comment by jitpack-io** [comment]
Hi @pardom 

Is there still an issue? It seems that the build log now shows the updated commit:
```
Build starting...
Start: Tue Dec 20 02:09:31 UTC 2016
Git:
1.2.0
commit 7fa50b4f39f5eadd2f55880530abef8965cb81cc
```

**Comment by pardom** [comment]
Are you looking at [this build.log](https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.0/build.log)? I still see this:

```
Build starting...
Start: Mon Dec 19 21:55:46 UTC 2016
Git:
1.2.0
commit c9c40602c6ccd8a052549cf751e05e87d4d63d8e
Author: Michael Pardo 
Date:   Mon Dec 19 16:17:16 2016 -0500

    Make API functional.


Run gradle build
Gradle build script
Found gradle version: 3.1.
Using sdkman gradle
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.14.32-xxxx-grs-ipv6-64 amd64

0m0.664s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Looking for android-library
Looking for com.android.application
Adding maven plugin
Running: gradle clean -Pgroup=com.github.pardom -Pversion=1.2.0 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
:clean
:lib:clean UP-TO-DATE
:lib:compileKotlin
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.pom
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.pom
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.pom
Download https://jcenter.bintray.com/org/assertj/assertj-parent-pom/1.2.6/assertj-parent-pom-1.2.6.pom
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.pom
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-parent/1.5.3/byte-buddy-parent-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis-parent/2.4/objenesis-parent-2.4.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.jar
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.jar
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.jar
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.jar
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.jar
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.jar
:lib:compileJava UP-TO-DATE
:lib:copyMainKotlinClasses
:lib:processResources UP-TO-DATE
:lib:classes UP-TO-DATE
:lib:jar
:lib:javadoc UP-TO-DATE
:lib:javadocJar
:lib:sourcesJar
:lib:install

BUILD SUCCESSFUL

Total time: 7.431 secs
Gradle exit code 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.github.pardom:lib:1.2.0
EXIT_CODE=0
2016-12-19T21:56:00.514003256Z
Exit code: 0

Build artifacts:
com.github.pardom:redux-observable-kotlin:1.2.0

Files: 
com/github/pardom/redux-observable-kotlin/1.2.0
com/github/pardom/redux-observable-kotlin/1.2.0/build.log
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-javadoc.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-sources.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.md5
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.sha1
```

**Comment by pardom** [comment]
I just deleted `1.2.0` again using the `removeBuild` button. I don't know if this is new behavior, but I haven't seen this happen before: the build starts up again automatically, whereas before I needed to trigger the build.

Here's the request/response from the remove request.

**Request**:
```
:authority:jitpack.io
:method:DELETE
:path:/api/builds/com.github.pardom/redux-observable-kotlin/1.2.0
:scheme:https
accept:application/json, text/javascript, */*; q=0.01
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8,it;q=0.6,es;q=0.4
cookie:__cfduid=<my-cookie>
origin:https://jitpack.io
referer:https://jitpack.io/
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
x-requested-with:XMLHttpRequest
```

**Response:**
```
access-control-allow-origin:*
cache-control:no-cache, no-store, must-revalidate
cf-ray:314328667bcb54e0-ORD
content-encoding:gzip
content-type:application/json; charset=utf-8
date:Tue, 20 Dec 2016 12:39:39 GMT
expires:0
pragma:no-cache
server:cloudflare-nginx
status:200
x-content-type-options:nosniff
x-frame-options:deny
x-xss-protection:1; mode=block

{
  "status" : "ok",
  "message" : "Starting delete"
}
```

**Comment by pardom** [comment]
Looking at the FAQ, it appears that what I have done in the past to update a release is not officially supported:

https://jitpack.io/docs/FAQ/

>**What happens if a tag or repository is deleted on GitHub?**
>
>If the project was already built then JitPack will continue serving the existing artifacts. It will not rebuild the project at the new tag. In case you need to redo a release the best option is to create a new version on GitHub.

>**Can I rebuild my project?**
>
>If your first build wasn’t successfull you can rebuild it. If you Sign In on JitPack.io then you’ll be able to remove the old build and re-requesting it will trigger a new build.
>
>See also https://jitpack.io/docs/BUILDING/#rebuilding

**Comment by pardom** [comment]
I've bumped the version until this can be resolved:
https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.1/

This seems like something that most maintainers would want control over. Can we add this as a maintainer feature?

**Comment by jitpack-io** [comment]
@pardom Could it be that the old log was cached in your browser? Perhaps try getting it from command line
We can see that it did get rebuilt with the new tag.

**Comment by pardom** [comment]
Here's the curl output

```shell
$ curl https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.0/build.log
Build starting...
Start: Mon Dec 19 21:55:46 UTC 2016
Git:
1.2.0
commit c9c40602c6ccd8a052549cf751e05e87d4d63d8e
Author: Michael Pardo 
Date:   Mon Dec 19 16:17:16 2016 -0500

    Make API functional.


Run gradle build
Gradle build script
Found gradle version: 3.1.
Using sdkman gradle
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.14.32-xxxx-grs-ipv6-64 amd64

0m0.664s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Looking for android-library
Looking for com.android.application
Adding maven plugin
Running: gradle clean -Pgroup=com.github.pardom -Pversion=1.2.0 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
:clean
:lib:clean UP-TO-DATE
:lib:compileKotlin
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.pom
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.pom
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.pom
Download https://jcenter.bintray.com/org/assertj/assertj-parent-pom/1.2.6/assertj-parent-pom-1.2.6.pom
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.pom
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-parent/1.5.3/byte-buddy-parent-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis-parent/2.4/objenesis-parent-2.4.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.jar
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.jar
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.jar
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.jar
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.jar
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.jar
:lib:compileJava UP-TO-DATE
:lib:copyMainKotlinClasses
:lib:processResources UP-TO-DATE
:lib:classes UP-TO-DATE
:lib:jar
:lib:javadoc UP-TO-DATE
:lib:javadocJar
:lib:sourcesJar
:lib:install

BUILD SUCCESSFUL

Total time: 7.431 secs
Gradle exit code 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.github.pardom:lib:1.2.0
EXIT_CODE=0
2016-12-19T21:56:00.514003256Z
Exit code: 0

Build artifacts:
com.github.pardom:redux-observable-kotlin:1.2.0

Files: 
com/github/pardom/redux-observable-kotlin/1.2.0
com/github/pardom/redux-observable-kotlin/1.2.0/build.log
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-javadoc.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-sources.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.md5
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.sha1
```

**Comment by pardom** [comment]
The same thing on a VPN:

```shell
$ curl https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.0/build.log
Build starting...
Start: Mon Dec 19 21:55:46 UTC 2016
Git:
1.2.0
commit c9c40602c6ccd8a052549cf751e05e87d4d63d8e
Author: Michael Pardo 
Date:   Mon Dec 19 16:17:16 2016 -0500

    Make API functional.


Run gradle build
Gradle build script
Found gradle version: 3.1.
Using sdkman gradle
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.14.32-xxxx-grs-ipv6-64 amd64

0m0.664s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Looking for android-library
Looking for com.android.application
Adding maven plugin
Running: gradle clean -Pgroup=com.github.pardom -Pversion=1.2.0 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
:clean
:lib:clean UP-TO-DATE
:lib:compileKotlin
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.pom
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.pom
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.pom
Download https://jcenter.bintray.com/org/assertj/assertj-parent-pom/1.2.6/assertj-parent-pom-1.2.6.pom
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.pom
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-parent/1.5.3/byte-buddy-parent-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis-parent/2.4/objenesis-parent-2.4.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.jar
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.jar
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.jar
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.jar
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.jar
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.jar
:lib:compileJava UP-TO-DATE
:lib:copyMainKotlinClasses
:lib:processResources UP-TO-DATE
:lib:classes UP-TO-DATE
:lib:jar
:lib:javadoc UP-TO-DATE
:lib:javadocJar
:lib:sourcesJar
:lib:install

BUILD SUCCESSFUL

Total time: 7.431 secs
Gradle exit code 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.github.pardom:lib:1.2.0
EXIT_CODE=0
2016-12-19T21:56:00.514003256Z
Exit code: 0

Build artifacts:
com.github.pardom:redux-observable-kotlin:1.2.0

Files: 
com/github/pardom/redux-observable-kotlin/1.2.0
com/github/pardom/redux-observable-kotlin/1.2.0/build.log
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-javadoc.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-sources.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.md5
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.sha1
```

and a remote server:

```shell
pardom@michaelpardo:~$ curl https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.0/build.log
Build starting...
Start: Tue Dec 20 19:36:51 UTC 2016
Git:
1.2.0
commit 7fa50b4f39f5eadd2f55880530abef8965cb81cc
Author: Michael Pardo 
Date:   Mon Dec 19 21:08:41 2016 -0500

    Update readme.


Run gradle build
Gradle build script
Found gradle version: 3.1.
Using sdkman gradle
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Linux 3.14.32-xxxx-grs-ipv6-64 amd64

0m0.672s
Getting a list of gradle tasks
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Looking for android-library
Looking for com.android.application
Adding maven plugin
Running: gradle clean -Pgroup=com.github.pardom -Pversion=1.2.0 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
:clean
:lib:clean UP-TO-DATE
:lib:compileKotlin
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.pom
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.pom
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.pom
Download https://jcenter.bintray.com/org/assertj/assertj-parent-pom/1.2.6/assertj-parent-pom-1.2.6.pom
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.pom
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-parent/1.5.3/byte-buddy-parent-1.5.3.pom
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis-parent/2.4/objenesis-parent-2.4.pom
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/1.2.0/jvm-redux-api-1.2.0.jar
Download https://jcenter.bintray.com/io/reactivex/rxjava/1.2.2/rxjava-1.2.2.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/api/1.2.0/api-1.2.0.jar
Download https://jitpack.io/com/github/jvm-redux/jvm-redux-api/specs/1.2.0/specs-1.2.0.jar
Download https://jcenter.bintray.com/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.jar
Download https://jcenter.bintray.com/org/mockito/mockito-core/2.2.16/mockito-core-2.2.16.jar
Download https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy/1.5.3/byte-buddy-1.5.3.jar
Download https://jcenter.bintray.com/net/bytebuddy/byte-buddy-agent/1.5.3/byte-buddy-agent-1.5.3.jar
Download https://jcenter.bintray.com/org/objenesis/objenesis/2.4/objenesis-2.4.jar
:lib:compileJava UP-TO-DATE
:lib:copyMainKotlinClasses
:lib:processResources UP-TO-DATE
:lib:classes UP-TO-DATE
:lib:jar
:lib:javadoc UP-TO-DATE
:lib:javadocJar
:lib:sourcesJar
:lib:install

BUILD SUCCESSFUL

Total time: 9.671 secs
Gradle exit code 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.github.pardom:lib:1.2.0
EXIT_CODE=0
2016-12-20T19:37:07.381954591Z
Exit code: 0

Build artifacts:
com.github.pardom:redux-observable-kotlin:1.2.0

Files: 
com/github/pardom/redux-observable-kotlin/1.2.0
com/github/pardom/redux-observable-kotlin/1.2.0/build.log
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-javadoc.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0-sources.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.jar
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.md5
com/github/pardom/redux-observable-kotlin/1.2.0/redux-observable-kotlin-1.2.0.pom.sha1
```

It looks like the remote server could find it, but not the VPN. Not sure how this is. I'll check my DNS settings.

**Comment by pardom** [comment]
Here are the headers:

**Local**
```shell
$ curl -I https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.0/build.log
HTTP/1.1 200 OK
Date: Wed, 21 Dec 2016 14:26:54 GMT
Content-Type: text/plain
Content-Length: 4487
Connection: keep-alive
Set-Cookie: __cfduid=<uid>; expires=Thu, 21-Dec-17 14:26:54 GMT; path=/; domain=.jitpack.io; HttpOnly
Cache-Control: public, max-age=1800
Last-Modified: Mon, 19 Dec 2016 16:55:49 EST
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
CF-Cache-Status: REVALIDATED
Expires: Wed, 21 Dec 2016 14:56:54 GMT
Server: cloudflare-nginx
CF-RAY: 314c0302ccf810ed-ORD
```

**Remote**
```shell
pardom@michaelpardo:~$ curl -I https://jitpack.io/com/github/pardom/redux-observable-kotlin/1.2.0/build.log
HTTP/1.1 200 OK
Date: Wed, 21 Dec 2016 14:26:29 GMT
Content-Type: text/plain
Content-Length: 4481
Connection: keep-alive
Set-Cookie: __cfduid=<uid> expires=Thu, 21-Dec-17 14:26:29 GMT; path=/; domain=.jitpack.io; HttpOnly
Cache-Control: public, max-age=1800
Last-Modified: Wed, 21 Dec 2016 03:58:29 EST
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
CF-Cache-Status: REVALIDATED
Expires: Wed, 21 Dec 2016 14:56:29 GMT
Server: cloudflare-nginx
CF-RAY: 314c0268aa7c06a9-EWR
```

`Date` and `Expires` appear to be correct, however, `Last-Modified` is quite different.

**Comment by pardom** [comment]
Can you use the `CF-RAY` header to trace the route on your end?

**Comment by jitpack-io** [comment]
Ok, found the problem. The CDN cache was not being cleared on rebuilds due to a bug.
We've fixed it now so it should be working as expected.
Thanks for all the detailed information! It helped us find the issue

**Comment by pardom** [comment]
Fixed! Thanks a ton!

**Comment by kuhadiyadharmesh** [comment]
Build starting...
Start: Thu Nov 1 07:17:33 UTC 2018 d1
Git:
0.1.24.0.22-0-gfcbf0db
commit fcbf0db14f97bc4592d918fe824354e102e9946b
Author: kuhadiyadharmesh@gmail.com 
Date:   Thu Nov 1 12:46:33 2018 +0530

    22


Run gradle build
Gradle build script
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-4.4-all.zip
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/jitpack/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4-all.zip to /home/jitpack/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1
Set executable permissions for: /home/jitpack/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4/bin/gradle

------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.10.0-28-generic amd64

0m3.840s
Getting tasks: ./gradlew tasks --all
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'build'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

WARNING:
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://jitpack.io/docs/

Adding maven plugin
Found android library build file in mylibrary
Running: ./gradlew clean -Pgroup=com.github.kuhadiyadharmesh -Pversion=0.1.24.0.22 install
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Djavax.xml.accessExternalSchema=all -Dhttps.protocols=TLSv1.2
Build file '/home/jitpack/build/build.gradle' is using GradleVersion from the private org.gradle.util package without an explicit import. Please either stop using these internal classes (recommended) or import them explicitly at the top of your build file. The implicit import is deprecated and will be removed in Gradle 5.0
Download https://repo.maven.apache.org/maven2/com/github/dcendents/android-maven-gradle-plugin/2.0/android-maven-gradle-plugin-2.0.pom
Download https://repo.maven.apache.org/maven2/com/github/dcendents/android-maven-gradle-plugin/2.0/android-maven-gradle-plugin-2.0.jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'build'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
EXIT_CODE=1
2018-11-01T07:17:47.564952777Z
Exit code: 1
No build artifacts found

**Comment by deepakbhatia** [comment]
> Ok, found the problem. The CDN cache was not being cleared on rebuilds due to a bug.
> We've fixed it now so it should be working as expected.
> Thanks for all the detailed information! It helped us find the issue

This problem is back. The build points to the correct commit id but the build served is still the old one. Probably the cached builds are not being deleted on rebuild.

**Comment by exotel-products** [comment]
> > Ok, found the problem. The CDN cache was not being cleared on rebuilds due to a bug.
> > We've fixed it now so it should be working as expected.
> > Thanks for all the detailed information! It helped us find the issue
> 
> This problem is back. The build points to the correct commit id but the build served is still the old one. Probably the cached builds are not being deleted on rebuild.

I am also facing the same issue, getting old build even after creating the new build. Also confirmed the build was correct by downloading aar file using logs. If its the cache issue can you guys tell the time period after which cache get expire?
