### ISSUE TITLE
Colorful/1.0 build

### ISSUE THREAD

**Issue by calintat** [jitpack/jitpack.io#1192]
Log https://jitpack.io/com/github/calintat/Colorful/1.0/build.log

**Comment by jitpack-io** [comment]
Fixed

**Comment by calintat** [comment]
It still doesn't work.
https://jitpack.io/com/github/calintat/colorful/1.0/build.log
