### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by kycqdhl3c** [jitpack/jitpack.io#1464]
Log https://jitpack.io/com/github/kycqdhl3c/KycqSupport/1.0.3/build.log

**Comment by ultraon** [comment]
I have the same issue today: Log https://jitpack.io/com/github/ultraon/DBFlow/3cfcf19938/build.log

**Comment by ultraon** [comment]
After some minutes i have new error: "...you need to accept the license agreements...", see log: https://jitpack.io/com/github/ultraon/DBFlow/31c06a1bf7/build.log

**Comment by kycqdhl3c** [comment]
I thought it was just my problem

**Comment by raxden** [comment]
same here.

**Comment by bruferrari** [comment]
same here, there's something we can do or it's a jitpack related problem?

**Comment by jitpack-io** [comment]
Hi all,

Sorry about that, should be fixed now.
Rebuilt the builds posted here but for others you can delete the failed build to re-try.

**Comment by duke79** [comment]
Not fixed. [Logs](https://jitpack.io/com/github/Baliyaan/Android-Library/-0.0.3-g89e8c40-2/build.log)

**Comment by jitpack-io** [comment]
@duke79 Could you retry?

**Comment by duke79** [comment]
It's working now. Thank you very much!
