### ISSUE TITLE
Provide maven-metadata.xml for multi-module projects

### ISSUE THREAD

**Issue by tynn** [jitpack/jitpack.io#1538]
Regarding [multi-module projects](https://jitpack.io/docs/BUILDING/#multi-module-projects) we do get the artifacts published to be consumed with.

     compile 'com.github.User.Repo:Module:Tag'

Sadly the _maven-metadata.xml_ is missing for these subprojects (see https://jitpack.io/berlin/volders/supplies/logging/maven-metadata.xml).

This file is needed to make wildcards work with these dependencies as well.

     compile 'com.github.User.Repo:Module:+'

This also relates to the last comment of #227  as well.

**Comment by jitpack-io** [comment]
Fixed

**Comment by adam-arold** [comment]
This is not fixed, I don't see the `maven-metadata.xml` file when I build my project on jitpack. See my buildlog [here](https://jitpack.io/com/github/Hexworks/Zircon/2018.1.3-SNAPSHOT/build.log)
How do I fix this?

**Comment by tynn** [comment]
@adam-arold, you have it on https://jitpack.io/com/github/Hexworks/Zircon/zircon.libgdx/2018.1.6-PREVIEW/maven-metadata.xml and on https://jitpack.io/com/github/Hexworks/Zircon/zircon.libgdx/2018.1.3-SNAPSHOT/maven-metadata-local.xml

This seems to be related to remote and local repos http://maven.apache.org/ref/3.2.5/maven-repository-metadata/ and also maybe to the `maven-publish` plugin, because `maven-metadata-local.xml` is also listed in `build.log` while `maven-metadata.xml` usually is not.

This issue was about not having the file all completely.

**Comment by jitpack-io** [comment]
@tynn Correct, maven-metadata.xml will not appear in the build log but it is available when requesting
