### ISSUE TITLE
specific branch support

### ISSUE THREAD

**Issue by meltzow** [jitpack/jitpack.io#193]
hi,
with -SNAPSHOT its possbile to stay at last commited version. But it looks this is branch independent right? all commits in all branches are resolved here right?
But I want only get new commits on a specific branch ("master" for example). How is this possbile?

Thank you.

**Comment by jitpack-io** [comment]
Hi @meltzow 

Thanks for the suggestion!
You're right, it's branch independent. We should fix that to always be master by default.

Currently specifying a branch for snapshots is not possible but it definitely would be a useful feature. Probably something like `master-SNAPSHOT`.
Will post an update on this ticket with progress.

**Comment by meltzow** [comment]
yes, sounds good.thank you

**Comment by katoquro** [comment]
+1
Snapshot builds from develep, that's what I need!

**Comment by jitpack-io** [comment]
small update - normal snapshots are now always from master

**Comment by peternied** [comment]
+1

**Comment by denis-itskovich** [comment]
+1

**Comment by jitpack-io** [comment]
Hi all,

Branch builds are now supported with the `branch-SNAPSHOT` version. 
If no branch is specified then it builds from master.

**Comment by peternied** [comment]
Thanks @jitpack-io !

**Comment by jitpack-io** [comment]
Most welcome!

**Comment by jitpack-io** [comment]
There was actually an issue getting branch snapshots from Gradle while it was working from Maven. Fixed now.

**Comment by elect86** [comment]
I'd like to fetch this specific branch

https://github.com/kotlintest/kotlintest/tree/release/2.0

So I wrote 

`testCompile("io.kotlintest:kotlintest:release/2.0-SNAPSHOT")`

but it doesn't resolve it, I guess the slash is the culprit.. or?
