### ISSUE TITLE
Subscription is not active right now

### ISSUE THREAD

**Issue by fin254** [jitpack/jitpack.io#4229]
Hi, I am currently encountering,
https://jitpack.io/net/tospay/xanda/root/tospay-lib-android/1.8.0/tospay-lib-android-1.8.0.pom,
the projects builds just fine but when pulling the library for usage i get the error
Could not GET 'https://jitpack.io/net/tospay/xanda/root/tospay-lib-android/1.8.0/tospay-lib-android-1.8.0.pom'. Received status code 403 from server: Forbidden
from a private repo, 3 days ago everything was working fine but now it does not seem to be working the subscription is already paid for. need assistance asap
Thank you!

**Comment by jitpack-io** [comment]
Hi,

Should be working now. Switched your subscription to `xanda.tospay.net/root`.

**Comment by myego2go** [comment]
Hi, I am facing same issue I already purchaed StarterY Plan but still getting this error.

Subscription is not active right now
Requested subscription: bitbucket.org/xxxxx. 
Your subscriptions are listed in https://jitpack.io/w/user
Please contact Support or repository admins if you need assistance.
