### ISSUE TITLE
Getting 401 for maven-metadata.xml of MPAndroidChart

### ISSUE THREAD

**Issue by Taskinator** [jitpack/jitpack.io#7049]
Failing link: https://jitpack.io/com/github/PhilJay/MPAndroidChart/maven-metadata.xml

The repository is public and the POM file is publicly accessible as expected: https://jitpack.io/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom

The `maven-metadata.xml` file however returns 401.

**Comment by jitpack-io** [comment]
Hi

Should be fixed now

**Comment by Taskinator** [comment]
@jitpack-io Thanks. I still get 401 though.

https://jitpack.io/com/github/PhilJay/MPAndroidChart/maven-metadata.xml

**Comment by weimingjue** [comment]
It's still a 401

**Comment by weimingjue** [comment]
> This issue was closed because it has been inactive for 14 days since being marked as stale.
Still 401, why do you always repeat this problem?
